-- Run after the existing LinguaX schema. This file only inserts records; it does not alter tables.
insert into public.lessons (title, category, difficulty, content) values
('Present Simple Essentials','Grammar','Beginner','{"overview":"Use the present simple for routines and facts.","explanation":"Use the base verb; add -s/-es with he, she, and it.","examples":[{"english":"She studies every day.","translation":"Dia belajar setiap hari."}]}'),
('Present Continuous','Grammar','Beginner','{"overview":"Describe actions happening now.","explanation":"Use am/is/are plus verb-ing.","examples":[{"english":"They are studying now.","translation":"Mereka sedang belajar sekarang."}]}'),
('Past Simple','Grammar','Beginner','{"overview":"Talk about finished actions in the past.","explanation":"Use verb two or did not plus base verb.","examples":[{"english":"I visited Bali last year.","translation":"Saya mengunjungi Bali tahun lalu."}]}'),
('Present Perfect','Grammar','Intermediate','{"overview":"Connect a past action to the present.","explanation":"Use have/has plus past participle.","examples":[{"english":"We have finished the task.","translation":"Kami sudah menyelesaikan tugas."}]}'),
('Future Forms','Grammar','Intermediate','{"overview":"Discuss plans and predictions.","explanation":"Use will for predictions and be going to for plans.","examples":[{"english":"I am going to practice tonight.","translation":"Saya akan berlatih malam ini."}]}'),
('Conditionals Zero and First','Grammar','Intermediate','{"overview":"Express facts and real future possibilities.","explanation":"Use if plus present; first conditional uses will in the result.","examples":[{"english":"If I study, I will improve.","translation":"Jika saya belajar, saya akan meningkat."}]}'),
('Conditionals Second and Third','Grammar','Advanced','{"overview":"Discuss unreal situations and regrets.","explanation":"Use past forms for second and had plus participle for third.","examples":[{"english":"If I had studied, I would have passed.","translation":"Jika saya belajar, saya pasti lulus."}]}'),
('Passive Voice','Grammar','Intermediate','{"overview":"Focus on the action rather than the actor.","explanation":"Use be plus past participle.","examples":[{"english":"The book was written in 2020.","translation":"Buku itu ditulis pada 2020."}]}'),
('Relative Clauses','Grammar','Advanced','{"overview":"Add information about people and things.","explanation":"Use who for people and which for things.","examples":[{"english":"The teacher who helped me is kind.","translation":"Guru yang membantu saya baik."}]}'),
('Subject-Verb Agreement','Grammar','Beginner','{"overview":"Make subjects and verbs match.","explanation":"Singular subjects take singular verbs.","examples":[{"english":"The list is long.","translation":"Daftarnya panjang."}]}'),
('Academic Word Families','Vocabulary','Beginner','{"overview":"Build vocabulary through related word forms.","explanation":"Learn noun, verb, adjective, and adverb forms together.","examples":[{"english":"Success comes from successful habits.","translation":"Kesuksesan datang dari kebiasaan yang berhasil."}]}'),
('Travel Vocabulary','Vocabulary','Beginner','{"overview":"Useful words for travel situations.","explanation":"Practice airport, hotel, and direction words.","examples":[{"english":"Where is the departure gate?","translation":"Di mana gerbang keberangkatan?"}]}'),
('Workplace Vocabulary','Vocabulary','Intermediate','{"overview":"Communicate professionally at work.","explanation":"Use precise terms for meetings and projects.","examples":[{"english":"We need to meet the deadline.","translation":"Kita perlu memenuhi tenggat waktu."}]}'),
('Education Vocabulary','Vocabulary','Intermediate','{"overview":"Discuss study and academic life.","explanation":"Learn words for research, courses, and evaluation.","examples":[{"english":"The research supports the claim.","translation":"Penelitian mendukung klaim tersebut."}]}'),
('Environment Vocabulary','Vocabulary','Intermediate','{"overview":"Discuss environmental issues.","explanation":"Use words such as sustainable and conservation.","examples":[{"english":"Recycling reduces waste.","translation":"Daur ulang mengurangi limbah."}]}'),
('Health Vocabulary','Vocabulary','Beginner','{"overview":"Speak about health and wellbeing.","explanation":"Practice symptoms, treatment, and prevention.","examples":[{"english":"Regular exercise improves health.","translation":"Olahraga teratur meningkatkan kesehatan."}]}'),
('Synonyms for TOEFL','Vocabulary','Advanced','{"overview":"Recognize similar meanings in TOEFL questions.","explanation":"Use context to choose the closest synonym.","examples":[{"english":"Essential means necessary.","translation":"Essential berarti necessary."}]}'),
('Academic Collocations','Vocabulary','Advanced','{"overview":"Use natural academic word combinations.","explanation":"Learn patterns such as conduct research.","examples":[{"english":"Scientists conduct research.","translation":"Ilmuwan melakukan penelitian."}]}'),
('Phrasal Verbs','Vocabulary','Intermediate','{"overview":"Understand common multi-word verbs.","explanation":"Meaning can differ from individual words.","examples":[{"english":"Please look up the word.","translation":"Tolong cari kata itu."}]}'),
('Idioms in Context','Vocabulary','Advanced','{"overview":"Understand non-literal expressions.","explanation":"Infer meaning from context.","examples":[{"english":"She is on cloud nine.","translation":"Dia sangat gembira."}]}'),
('Reading Main Ideas','Reading','Intermediate','{"overview":"Identify the author’s central message.","explanation":"Read topic sentences and repeated ideas.","examples":[{"english":"The main idea summarizes the passage.","translation":"Gagasan utama merangkum bacaan."}]}'),
('Listening for Details','Listening','Intermediate','{"overview":"Catch names, numbers, and supporting facts.","explanation":"Listen for signal words and take brief notes.","examples":[{"english":"The lecture begins at nine.","translation":"Kuliah dimulai pukul sembilan."}]}'),
('TOEFL Structure Strategy','TOEFL','Intermediate','{"overview":"Approach structure questions efficiently.","explanation":"Find the subject and verb before checking choices.","examples":[{"english":"Each student has a book.","translation":"Setiap siswa memiliki buku."}]}'),
('TOEFL Reading Strategy','TOEFL','Advanced','{"overview":"Manage time in TOEFL reading.","explanation":"Skim structure, then scan for evidence.","examples":[{"english":"Find the evidence in the passage.","translation":"Temukan bukti dalam bacaan."}]}'),
('TOEFL Writing Foundations','TOEFL','Advanced','{"overview":"Write a focused TOEFL response.","explanation":"Use a clear thesis, reasons, and examples.","examples":[{"english":"In my opinion, public transport is beneficial.","translation":"Menurut saya, transportasi umum bermanfaat."}]}'),
('TOEFL Listening Strategy','TOEFL','Intermediate','{"overview":"Follow TOEFL lectures effectively.","explanation":"Predict the topic and note key transitions.","examples":[{"english":"However signals a contrast.","translation":"However menandakan perbedaan."}]}'),
('TOEFL Speaking Foundations','TOEFL','Advanced','{"overview":"Give a clear TOEFL speaking response.","explanation":"State, support, and summarize your opinion.","examples":[{"english":"I prefer studying in the morning because I can focus.","translation":"Saya lebih suka belajar pagi karena bisa fokus."}]}');

insert into public.quiz_questions (lesson_id, question, options, answer, explanation)
select id, 'Choose the correct sentence.', '["She study every day.","She studies every day.","She studying every day.","She studied every day now."]'::jsonb, 'She studies every day.', 'With she, use studies in the present simple.' from public.lessons where title = 'Present Simple Essentials'
union all select id, 'Which form describes an action happening now?', '["I work.","I am working.","I worked.","I have work."]'::jsonb, 'I am working.', 'Present continuous uses am/is/are plus -ing.' from public.lessons where title = 'Present Continuous'
union all select id, 'Choose the past simple form.', '["go","went","gone","going"]'::jsonb, 'went', 'Went is the past simple of go.' from public.lessons where title = 'Past Simple'
union all select id, 'Complete: I ___ finished my homework.', '["has","have","am","did"]'::jsonb, 'have', 'Use have with I in present perfect.' from public.lessons where title = 'Present Perfect'
union all select id, 'Complete: If it rains, we ___ home.', '["stay","will stay","stayed","would stay"]'::jsonb, 'will stay', 'First conditional uses will in the result clause.' from public.lessons where title = 'Conditionals Zero and First'
union all select id, 'Which is passive voice?', '["People build houses.","Houses are built.","People are build houses.","Houses build people."]'::jsonb, 'Houses are built.', 'Passive voice is be plus past participle.' from public.lessons where title = 'Passive Voice'
union all select id, 'Choose the correct agreement.', '["The list are long.","The list is long.","The list be long.","The list were long."]'::jsonb, 'The list is long.', 'List is singular, so use is.' from public.lessons where title = 'Subject-Verb Agreement'
union all select id, 'Which word is closest to necessary?', '["optional","essential","rare","ordinary"]'::jsonb, 'essential', 'Essential means necessary.' from public.lessons where title = 'Synonyms for TOEFL'
union all select id, 'Complete: Scientists ___ research.', '["do","conduct","make","build"]'::jsonb, 'conduct', 'Conduct research is a common academic collocation.' from public.lessons where title = 'Academic Collocations'
union all select id, 'What is the main idea?', '["A minor example","The central message","A new vocabulary word","The author name"]'::jsonb, 'The central message', 'The main idea is the author’s central message.' from public.lessons where title = 'Reading Main Ideas'
union all select id, 'What should you find first in a structure question?', '["The longest word","Subject and verb","The final punctuation","A synonym"]'::jsonb, 'Subject and verb', 'Finding subject and verb reveals the sentence structure.' from public.lessons where title = 'TOEFL Structure Strategy';

insert into public.quiz_questions (lesson_id, question, options, answer, explanation)
select id, 'Which word often signals a contrast in a lecture?', '["Because","However","Therefore","For example"]'::jsonb, 'However', 'However introduces contrasting information.' from public.lessons where title = 'TOEFL Listening Strategy'
union all select id, 'What is a good TOEFL speaking response structure?', '["State, support, summarize","Question, memorize, repeat","Read, translate, stop","Only give an example"]'::jsonb, 'State, support, summarize', 'A direct opinion, support, and short summary creates a clear answer.' from public.lessons where title = 'TOEFL Speaking Foundations';

insert into public.achievements (name, description, reward) values
('First Lesson','Complete your first lesson.',25),('Grammar Beginner','Complete a Grammar lesson.',50),('Vocabulary Master','Complete a Vocabulary lesson.',50),('7 Days Streak','Maintain a seven-day learning streak.',100),('TOEFL Starter','Reach 1000 EXP.',100)
on conflict (name) do nothing;

insert into public.daily_challenges (title, reward_exp, reward_coin) values
('Complete one lesson',50,10),('Finish a quiz',30,5),('Learn vocabulary',20,5);
