"use client";
import Link from "next/link";
import { ArrowLeft, Play } from "lucide-react";
import { ProtectedPage } from "@/components/protected-page";
import { learningService } from "@/services/learning-service";
import type { Lesson } from "@/types/learning";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
export default function LessonPage() { return <ProtectedPage><LessonView /></ProtectedPage>; }
function LessonView() { const params = useParams<{id:string}>(); const [lesson,setLesson] = useState<Lesson | null>(null); const [error,setError]=useState(""); useEffect(()=>{learningService.getLesson(params.id).then(({data,error})=>{setLesson(data);setError(error?.message||"")})},[params.id]); if(error) return <PageMessage text={`Lesson unavailable: ${error}`}/>; if(!lesson) return <PageMessage text="Loading lesson…"/>; return <main className="min-h-screen bg-[#09111f] text-slate-100"><div className="mx-auto max-w-3xl px-5 py-8"><Link href="/learn" className="inline-flex items-center gap-2 text-sm text-cyan-300"><ArrowLeft size={16}/> All lessons</Link><span className="mt-8 inline-block rounded-full bg-cyan-400/10 px-3 py-1 text-xs text-cyan-300">{lesson.category} · {lesson.difficulty}</span><h1 className="mt-4 text-3xl font-bold">{lesson.title}</h1><p className="mt-4 text-lg leading-8 text-slate-300">{lesson.content?.overview}</p><section className="glass mt-7 rounded-3xl p-6"><h2 className="text-xl font-bold">Explanation</h2><p className="mt-3 leading-7 text-slate-300">{lesson.content?.explanation || "Review this lesson, then test yourself in the quiz."}</p></section>{lesson.content?.examples?.length ? <section className="glass mt-5 rounded-3xl p-6"><h2 className="text-xl font-bold">Examples</h2><div className="mt-4 space-y-3">{lesson.content.examples.map((example,i)=><div key={i} className="rounded-xl bg-white/5 p-4"><p className="font-medium">{example.english}</p>{example.translation && <p className="mt-1 text-sm text-slate-400">{example.translation}</p>}</div>)}</div></section> : null}<Link href={`/quiz/${lesson.id}`} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950"><Play size={17}/> Start quiz</Link></div></main>; }
function PageMessage({text}:{text:string}) { return <main className="grid min-h-screen place-items-center bg-[#09111f] p-5 text-center text-slate-300">{text}</main>; }
