"use client";
import Link from "next/link";
import { BookOpen, Filter } from "lucide-react";
import { ProtectedPage } from "@/components/protected-page";
import { learningService } from "@/services/learning-service";
import type { Lesson } from "@/types/learning";
import { useEffect, useState } from "react";
const categories = ["All", "Grammar", "Vocabulary", "Reading", "Listening", "TOEFL"];
const difficulties = ["All", "Beginner", "Intermediate", "Advanced"];
export default function LearnPage() { return <ProtectedPage><Learn /></ProtectedPage>; }
function Learn() { const [category, setCategory] = useState("All"); const [difficulty, setDifficulty] = useState("All"); const [lessons, setLessons] = useState<Lesson[]>([]); const [error, setError] = useState(""); useEffect(() => { learningService.getLessons(category, difficulty).then(({data,error}) => { setLessons(data); setError(error?.message || ""); }); }, [category, difficulty]); return <main className="min-h-screen bg-[#09111f] text-slate-100"><header className="border-b border-white/10 px-5 py-4"><div className="mx-auto flex max-w-6xl items-center justify-between"><Link href="/dashboard" className="text-xl font-bold">Lingua<span className="text-cyan-400">X</span></Link><Link href="/dashboard" className="text-sm text-slate-400">Dashboard</Link></div></header><div className="mx-auto max-w-6xl px-5 py-9"><p className="text-sm font-semibold text-cyan-400">LEARNING LIBRARY</p><h1 className="mt-2 text-3xl font-bold">Choose your next lesson</h1><p className="mt-2 text-slate-400">Every lesson and quiz is loaded from your Supabase curriculum.</p><div className="glass mt-7 flex flex-col gap-4 rounded-2xl p-4 sm:flex-row"><div className="flex items-center gap-2 text-slate-400"><Filter size={17}/><span className="text-sm">Filter</span></div><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl bg-white/10 px-3 py-2 text-sm outline-none"><option>All</option>{categories.slice(1).map(x=><option key={x}>{x}</option>)}</select><select value={difficulty} onChange={e=>setDifficulty(e.target.value)} className="rounded-xl bg-white/10 px-3 py-2 text-sm outline-none"><option>All</option>{difficulties.slice(1).map(x=><option key={x}>{x}</option>)}</select></div>{error ? <p className="mt-6 text-rose-300">Could not load lessons: {error}</p> : <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{lessons.map(lesson=><Link key={lesson.id} href={`/learn/${lesson.id}`} className="glass rounded-3xl p-5 transition hover:-translate-y-1"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-cyan-400/15 text-cyan-300"><BookOpen size={20}/></div><div className="mt-5 flex items-center justify-between"><span className="text-xs font-semibold text-cyan-300">{lesson.category}</span><span className="rounded-full bg-white/10 px-2 py-1 text-xs text-slate-400">{lesson.difficulty}</span></div><h2 className="mt-3 text-lg font-bold">{lesson.title}</h2><p className="mt-2 line-clamp-2 text-sm text-slate-400">{lesson.content?.overview || "Open lesson"}</p></Link>)}</div>}{!error && lessons.length === 0 && <p className="mt-8 text-slate-400">No lessons match this filter. Run the seed SQL if your curriculum is empty.</p>}</div></main>; }
