"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { signInWithEmail, signInWithGoogle, signUpWithEmail } from "@/lib/auth";

export default function LoginPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [mode, setMode] = useState<"login" | "register">("login"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); const { error } = mode === "login" ? await signInWithEmail(email, password) : await signUpWithEmail(email, password); setMessage(error?.message || (mode === "register" ? "Check your email to confirm your account." : "Signed in successfully.")); setBusy(false); }
  async function google() { setBusy(true); const { error } = await signInWithGoogle(); if (error) { setMessage(error.message); setBusy(false); } }
  return <main className="grid min-h-screen place-items-center bg-[#09111f] p-5 text-slate-100"><section className="glass w-full max-w-md rounded-3xl p-7"><Link href="/" className="text-sm text-cyan-300">← LinguaX</Link><h1 className="mt-6 text-2xl font-bold">{mode === "login" ? "Welcome back" : "Create your account"}</h1><p className="mt-2 text-sm text-slate-400">Continue your TOEFL learning journey.</p><button onClick={google} disabled={busy} className="mt-6 w-full rounded-xl border border-white/15 px-4 py-3 text-sm font-semibold disabled:opacity-50">Continue with Google</button><div className="my-5 border-t border-white/10"/><form onSubmit={submit} className="space-y-3"><input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="Email address" className="w-full rounded-xl bg-white/8 px-4 py-3 text-sm outline-none ring-cyan-400 focus:ring-1"/><input required minLength={6} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Password" className="w-full rounded-xl bg-white/8 px-4 py-3 text-sm outline-none ring-cyan-400 focus:ring-1"/><button disabled={busy} className="w-full rounded-xl bg-cyan-400 px-4 py-3 text-sm font-bold text-slate-950 disabled:opacity-50">{busy ? "Please wait…" : mode === "login" ? "Sign in" : "Create account"}</button></form>{message && <p className="mt-4 text-sm text-cyan-200">{message}</p>}<button onClick={() => { setMode(mode === "login" ? "register" : "login"); setMessage(""); }} className="mt-5 text-sm text-slate-400">{mode === "login" ? "New to LinguaX? Create an account" : "Already have an account? Sign in"}</button></section></main>;
}
