"use client";
import Link from "next/link";
import { CheckCircle2 } from "lucide-react";
import { ProtectedPage } from "@/components/protected-page";
import { useAuth } from "@/hooks/use-auth";
import { learningService } from "@/services/learning-service";
import type { QuizQuestion } from "@/types/learning";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
export default function QuizPage() { return <ProtectedPage><Quiz /></ProtectedPage>; }
function Quiz() { const { lessonId } = useParams<{lessonId:string}>(); const { user } = useAuth(); const [questions,setQuestions]=useState<QuizQuestion[]>([]); const [answers,setAnswers]=useState<Record<string,string>>({}); const [submitted,setSubmitted]=useState(false); const [saving,setSaving]=useState(false); const [result,setResult]=useState<{score:number;xp:number;coins:number}|null>(null); const [error,setError]=useState("");
 useEffect(()=>{learningService.getQuestions(lessonId).then(({data,error})=>{setQuestions(data);setError(error?.message||"")})},[lessonId]);
 async function finish(){ if(!user || answers && Object.keys(answers).length !== questions.length) return; setSaving(true); const score=Math.round(questions.filter(q=>answers[q.id]===q.answer).length/questions.length*100); const saved=await learningService.recordQuiz(user.id,lessonId,score); if(saved.error)setError(saved.error.message); else {setResult({score,xp:saved.xp,coins:saved.coins});setSubmitted(true)} setSaving(false); }
 if(error) return <Message text={`Quiz error: ${error}`}/>; if(!questions.length) return <Message text="Loading quiz…"/>;
 if(submitted && result) return <main className="grid min-h-screen place-items-center bg-[#09111f] p-5 text-slate-100"><section className="glass w-full max-w-lg rounded-3xl p-8 text-center"><CheckCircle2 className="mx-auto text-emerald-400" size={48}/><h1 className="mt-5 text-3xl font-bold">Quiz complete</h1><p className="mt-3 text-5xl font-bold text-cyan-300">{result.score}%</p><p className="mt-4 text-slate-400">You earned +{result.xp} XP and +{result.coins} coins.</p><div className="mt-6 space-y-3 text-left">{questions.map(q=><div key={q.id} className="rounded-xl bg-white/5 p-3 text-sm"><p className={answers[q.id]===q.answer?"text-emerald-300":"text-rose-300"}>{answers[q.id]===q.answer?"Correct":"Review"}: {q.explanation}</p></div>)}</div><Link href="/dashboard" className="mt-7 inline-block rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950">Back to dashboard</Link></section></main>;
 return <main className="min-h-screen bg-[#09111f] text-slate-100"><div className="mx-auto max-w-3xl px-5 py-8"><Link href={`/learn/${lessonId}`} className="text-sm text-cyan-300">← Back to lesson</Link><h1 className="mt-6 text-3xl font-bold">Lesson quiz</h1><p className="mt-2 text-slate-400">Choose the best answer for every question.</p><div className="mt-8 space-y-5">{questions.map((q,index)=><section key={q.id} className="glass rounded-3xl p-6"><p className="text-sm text-cyan-300">Question {index+1} of {questions.length}</p><h2 className="mt-3 text-lg font-semibold">{q.question}</h2><div className="mt-5 grid gap-3">{q.options.map(option=><button key={option} onClick={()=>setAnswers({...answers,[q.id]:option})} className={`rounded-xl border p-4 text-left text-sm transition ${answers[q.id]===option?"border-cyan-400 bg-cyan-400/10 text-cyan-100":"border-white/10 bg-white/5 hover:border-white/30"}`}>{option}</button>)}</div></section>)}</div><button disabled={saving || Object.keys(answers).length!==questions.length} onClick={finish} className="mt-6 rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950 disabled:cursor-not-allowed disabled:opacity-50">{saving?"Saving result…":"Finish quiz"}</button></div></main>;
}
function Message({text}:{text:string}){return <main className="grid min-h-screen place-items-center bg-[#09111f] text-slate-300">{text}</main>}
