"use client";

import { motion } from "framer-motion";
import { ArrowRight, BookOpen, BrainCircuit, CheckCircle2, ChevronRight, Clock3, Flame, Headphones, MessageSquareText, Mic2, PenLine, Play, Sparkles, Trophy, Volume2 } from "lucide-react";
import { useState } from "react";

const modules = [
  { name: "Grammar", icon: BookOpen, color: "from-violet-500 to-purple-600", progress: 68, lessons: "12 lessons" },
  { name: "Vocabulary", icon: Volume2, color: "from-cyan-500 to-blue-600", progress: 42, lessons: "246 words" },
  { name: "Listening", icon: Headphones, color: "from-pink-500 to-rose-600", progress: 25, lessons: "8 practices" },
  { name: "Speaking", icon: Mic2, color: "from-amber-400 to-orange-600", progress: 16, lessons: "Start now" },
  { name: "Writing", icon: PenLine, color: "from-emerald-400 to-teal-600", progress: 34, lessons: "6 prompts" },
  { name: "TOEFL", icon: Trophy, color: "from-indigo-500 to-blue-600", progress: 10, lessons: "Mock test" },
];

export default function Home() {
  const [dark, setDark] = useState(true);
  const [started, setStarted] = useState(false);
  return <main className={dark ? "min-h-screen bg-[#09111f] text-slate-100" : "min-h-screen bg-slate-50 text-slate-900"}>
    <nav className="sticky top-0 z-20 border-b border-white/10 bg-[#09111f]/75 px-5 py-4 backdrop-blur-xl md:px-10">
      <div className="mx-auto flex max-w-7xl items-center justify-between"><div className="flex items-center gap-2 text-xl font-bold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-cyan-400 to-blue-600 text-white"><Sparkles size={18}/></span>Lingua<span className="text-cyan-400">X</span></div>
      <div className="hidden gap-7 text-sm text-slate-300 md:flex"><a href="#learn">Learn</a><a href="#progress">Progress</a><a href="#tutor">AI Tutor</a></div><div className="flex items-center gap-3"><button aria-label="Toggle theme" onClick={()=>setDark(!dark)} className="rounded-full border border-white/15 px-3 py-1.5 text-xs">{dark ? "☼ Light" : "☾ Dark"}</button><button className="rounded-xl bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950">Profile</button></div></div>
    </nav>
    <div className="mx-auto max-w-7xl px-5 py-8 md:px-10">
      <section className="mb-9 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-sm font-medium text-cyan-400">Friday, July 24 · Keep your streak alive!</p><h1 className="text-3xl font-bold tracking-tight md:text-4xl">Hello, Aisha <span className="inline-block animate-bounce">👋</span></h1><p className="mt-2 text-slate-400">Your TOEFL journey is looking stronger every day.</p></div><button onClick={()=>setStarted(true)} className="flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-cyan-400 to-blue-500 px-5 py-3 font-semibold text-slate-950 shadow-lg shadow-cyan-500/20"><Play size={17} fill="currentColor"/> {started ? "Lesson in progress" : "Continue learning"}</button></section>
      <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Stat label="Current level" value="Level 12" hint="Scholar" icon={<Trophy/>} tone="violet"/><Stat label="Experience" value="2,840 XP" hint="160 XP to level up" icon={<Sparkles/>} tone="cyan"/><Stat label="Daily streak" value="14 days" hint="Personal best: 21" icon={<Flame/>} tone="orange"/><Stat label="TOEFL prediction" value="92 / 120" hint="↑ 6 pts this month" icon={<BrainCircuit/>} tone="pink"/>
      </section>
      <section className="mt-5 grid gap-5 lg:grid-cols-3">
        <motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="glass relative overflow-hidden rounded-3xl p-6 lg:col-span-2"><div className="absolute -right-14 -top-16 h-48 w-48 rounded-full bg-cyan-400/15 blur-3xl"/><div className="relative flex justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-cyan-300"><Sparkles size={16}/> DAILY CHALLENGE</div><h2 className="mt-3 text-2xl font-bold">Master conditional sentences</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-400">Choose the right conditional form, then make it your own in a real conversation.</p></div><div className="hidden h-16 w-16 items-center justify-center rounded-2xl bg-cyan-400/10 text-3xl sm:flex">🎯</div></div><div className="relative mt-6 flex flex-wrap items-center gap-3"><span className="rounded-full bg-white/8 px-3 py-1.5 text-xs"><Clock3 className="mr-1 inline" size={13}/> 8 minutes</span><span className="rounded-full bg-amber-400/10 px-3 py-1.5 text-xs text-amber-300">+80 XP</span><span className="rounded-full bg-yellow-400/10 px-3 py-1.5 text-xs text-yellow-300">+25 coins</span><button className="ml-auto flex items-center gap-1 text-sm font-semibold text-cyan-300">Take challenge <ArrowRight size={15}/></button></div></motion.div>
        <div className="glass rounded-3xl p-6"><div className="flex items-center justify-between"><h2 className="font-bold">Today&apos;s mission</h2><span className="text-xs text-slate-400">2 / 3</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full w-2/3 rounded-full bg-gradient-to-r from-cyan-400 to-blue-500"/></div><div className="mt-5 space-y-3 text-sm"><Mission done text="Complete 1 grammar lesson"/><Mission done text="Review 10 flashcards"/><Mission text="Practice speaking for 5 min"/></div></div>
      </section>
      <section id="progress" className="mt-5 grid gap-5 lg:grid-cols-3"><div className="glass rounded-3xl p-6 lg:col-span-2"><div className="flex items-center justify-between"><div><h2 className="font-bold">Learning progress</h2><p className="mt-1 text-sm text-slate-400">This week&apos;s focused practice</p></div><button className="text-sm text-cyan-300">View report <ChevronRight className="inline" size={16}/></button></div><div className="mt-7 flex h-32 items-end justify-between gap-3">{[35,62,46,84,55,72,92].map((v,i)=><div key={i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-lg bg-gradient-to-t from-blue-600 to-cyan-400" style={{height:`${v}%`}}/><span className="text-xs text-slate-500">{["M","T","W","T","F","S","S"][i]}</span></div>)}</div></div><div className="glass rounded-3xl p-6"><h2 className="font-bold">Weakest skill</h2><div className="mt-5 flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-pink-400/10 text-pink-300"><Headphones/></div><div><p className="font-semibold">Listening</p><p className="text-sm text-slate-400">Accuracy: 58%</p></div></div><p className="mt-5 text-sm leading-6 text-slate-400">Try short daily audio drills to improve your inference and detail recognition.</p><button className="mt-4 text-sm font-semibold text-cyan-300">Practice now →</button></div></section>
      <section id="learn" className="mt-10"><div className="mb-5 flex items-end justify-between"><div><p className="text-sm font-semibold text-cyan-400">LEARNING PATH</p><h2 className="mt-1 text-2xl font-bold">Build every TOEFL skill</h2></div><button className="text-sm text-slate-400">Explore all</button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{modules.map((m,i)=><motion.a whileHover={{y:-4}} href="#" key={m.name} className="glass group rounded-3xl p-5"><div className={`grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br ${m.color} text-white shadow-lg`}><m.icon size={21}/></div><div className="mt-5 flex justify-between"><div><h3 className="font-bold">{m.name}</h3><p className="mt-1 text-xs text-slate-400">{m.lessons}</p></div><ChevronRight className="text-slate-500 transition group-hover:text-cyan-300"/></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full bg-gradient-to-r ${m.color}`} style={{width:`${m.progress}%`}}/></div><p className="mt-2 text-right text-xs text-slate-500">{m.progress}% completed</p></motion.a>)}</div></section>
      <section id="tutor" className="mt-10 rounded-3xl border border-cyan-300/15 bg-gradient-to-br from-cyan-500/15 via-blue-500/10 to-violet-500/15 p-6 md:p-8"><div className="flex flex-col items-start justify-between gap-5 md:flex-row md:items-center"><div className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-cyan-400 text-slate-950"><MessageSquareText/></div><div><h2 className="text-xl font-bold">Meet your AI English tutor</h2><p className="mt-1 max-w-xl text-sm leading-6 text-slate-300">Ask in Indonesian, practise freely, and get clear explanations, examples, exercises, and common mistakes.</p></div></div><a href="/tutor" className="whitespace-nowrap rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-900">Ask Lingua AI</a></div></section>
    </div>
  </main>
}
function Stat({label,value,hint,icon,tone}:{label:string,value:string,hint:string,icon:React.ReactNode,tone:string}) { return <div className="glass rounded-3xl p-5"><div className={`flex h-10 w-10 items-center justify-center rounded-xl bg-${tone}-400/10 text-${tone}-300`}>{icon}</div><p className="mt-4 text-xs font-medium uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xl font-bold">{value}</p><p className="mt-1 text-xs text-slate-400">{hint}</p></div> }
function Mission({text,done=false}:{text:string,done?:boolean}) { return <div className={`flex items-center gap-2 ${done?"text-slate-400 line-through":"text-slate-200"}`}><CheckCircle2 size={17} className={done?"text-cyan-400":"text-slate-600"}/>{text}</div> }
