"use client";
import { ArrowLeft, Loader2, Send, Sparkles } from "lucide-react";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useAuth } from "@/hooks/use-auth";
export default function TutorPage() {
 const [message,setMessage]=useState(""); const [answer,setAnswer]=useState(""); const [loading,setLoading]=useState(false); const { user } = useAuth();
 async function ask(e:FormEvent){e.preventDefault(); if(!message.trim())return; setLoading(true); setAnswer(""); const { data } = await (await import("@/lib/supabase/client")).getSupabaseClient().auth.getSession(); const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json",...(data.session?{Authorization:`Bearer ${data.session.access_token}`}:{})},body:JSON.stringify({message})}); const d=await r.json(); setAnswer(d.answer||d.error); setLoading(false)}
 return <main className="min-h-screen bg-[#09111f] px-5 py-8 text-slate-100"><div className="mx-auto max-w-3xl"><Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-400"><ArrowLeft size={16}/> Dashboard</Link><div className="mt-10 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-cyan-400 text-slate-950"><Sparkles/></span><h1 className="mt-4 text-3xl font-bold">Lingua AI Tutor</h1><p className="mt-2 text-slate-400">Belajar Bahasa Inggris dengan penjelasan yang jelas.</p></div><div className="glass mt-8 min-h-60 rounded-3xl p-6"><p className="whitespace-pre-wrap leading-7 text-slate-200">{answer || "Tanyakan grammar, kosa kata, atau strategi TOEFL apa pun. Saya akan menjawab dalam Bahasa Indonesia dengan contoh dan latihan."}</p>{loading&&<Loader2 className="mt-5 animate-spin text-cyan-400"/>}</div><form onSubmit={ask} className="glass mt-5 flex gap-3 rounded-2xl p-2"><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Contoh: Kapan memakai present perfect?" className="min-w-0 flex-1 bg-transparent px-3 text-sm outline-none placeholder:text-slate-500"/><button disabled={loading} className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-400 text-slate-950 disabled:opacity-50"><Send size={17}/></button></form></div></main>
}
