"use client";
import Link from "next/link";
import { Award, BookOpen, Flame, Trophy } from "lucide-react";
import { ProtectedPage } from "@/components/protected-page";
import { useAuth } from "@/hooks/use-auth";
import { learningService } from "@/services/learning-service";
import type { Profile } from "@/types/learning";
import { useEffect, useState } from "react";
export default function ProfilePage() { return <ProtectedPage><ProfileView /></ProtectedPage>; }
function ProfileView() { const { user } = useAuth(); const [profile,setProfile]=useState<Profile|null>(null); const [completed,setCompleted]=useState(0); const [awards,setAwards]=useState<{achievements:{id:string;name:string;description:string}|null}[]>([]); useEffect(()=>{if(!user)return; learningService.getDashboard(user.id).then(data=>{setProfile(data.profile);setCompleted(data.progress.length);setAwards(data.achievements as typeof awards)})},[user]); if(!profile) return <main className="grid min-h-screen place-items-center bg-[#09111f] text-cyan-300">Loading profile…</main>; return <main className="min-h-screen bg-[#09111f] text-slate-100"><div className="mx-auto max-w-4xl px-5 py-8"><Link href="/dashboard" className="text-sm text-cyan-300">← Dashboard</Link><section className="glass mt-6 rounded-3xl p-7"><div className="flex items-center gap-5"><div className="grid h-16 w-16 place-items-center overflow-hidden rounded-2xl bg-cyan-400/15 text-2xl text-cyan-300">{profile.avatar ? <img src={profile.avatar} alt="Profile" className="h-full w-full object-cover"/> : profile.username?.slice(0,1).toUpperCase()}</div><div><h1 className="text-2xl font-bold">{profile.username || "Learner"}</h1><p className="text-sm text-slate-400">{profile.email}</p><p className="mt-1 text-sm text-cyan-300">Level {Math.floor(profile.exp/500)+1} · {profile.exp} XP</p></div></div></section><section className="mt-5 grid gap-4 sm:grid-cols-3"><Tile icon={<BookOpen/>} value={String(completed)} label="Completed lessons"/><Tile icon={<Flame/>} value={`${profile.streak} days`} label="Current streak"/><Tile icon={<Trophy/>} value={String(profile.coins)} label="Coins"/></section><section className="glass mt-5 rounded-3xl p-6"><div className="flex items-center gap-2"><Award className="text-amber-300"/><h2 className="font-bold">Achievements</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{awards.length ? awards.map(({achievements})=>achievements&&<div key={achievements.id} className="rounded-xl bg-white/5 p-4"><p className="font-semibold">{achievements.name}</p><p className="mt-1 text-sm text-slate-400">{achievements.description}</p></div>) : <p className="text-sm text-slate-400">Complete lessons to unlock achievements.</p>}</div></section></div></main>; }
function Tile({icon,value,label}:{icon:React.ReactNode;value:string;label:string}) { return <div className="glass rounded-3xl p-5"><div className="text-cyan-300">{icon}</div><p className="mt-3 text-2xl font-bold">{value}</p><p className="text-sm text-slate-400">{label}</p></div> }
